refactor: return client version by default
bacalhau-project/bacalhau pull request #3968
Opened 2024-05-01 17:22 UTC by frrist

- replaces the '--client' flag on the `version` command with '--server'. The default value of '--server' is false. This results in the `version` command always succeeding.
- closes #3308

2024-05-01 17:42 UTC, aronchick approved these changes

2024-05-02 11:48 UTC, wdbaruni requested changes
I don't think we need this change given you introduced a short timeout when querying server version here https://github.com/bacalhau-project/bacalhau/pull/3964

It might make sense to give it sometime and see if that changes hits the sweet spot of improved user experience where they can easily know if their clients are outdated, and  not hang if client is disconnected. Feel free to reduce the 3 seconds timeout to 2 seconds if you believe it is not short enough

2024-05-02 14:55 UTC, aronchick commented
> I don't think we need this change given you introduced a short timeout when querying server version here #3964
> 
> It might make sense to give it sometime and see if that changes hits the sweet spot of improved user experience where they can easily know if their clients are outdated, and not hang if client is disconnected. Feel free to reduce the 3 seconds timeout to 2 seconds if you believe it is not short enough
> 
> @aronchick what do you think?

I'll be honest, I can see both sides. 

Is there a scenario where someone should be able to get the version of a binary without connecting to a server? yes - i just downloaded it.

Is the function of our client app ONLY to connect to the server? Yes, so it makes sense we do that too.

I _guess_ the ideal user experience, on first download would for this to come back in 1 second.

```
 CLIENT  SERVER  LATEST  UPDATE MESSAGE
 v1.3.0  Disconnected  v1.3.0
```
 
And the moment API_Server (or whatever) is set - 

```
 CLIENT  SERVER  LATEST  UPDATE MESSAGE
 v1.3.0  v1.3.0  v1.3.0
 ```
 
 We should also have a `bacalhau connect <IP_ADDRESS>` command....

2024-05-07 06:13 UTC, wdbaruni commented
I like the suggestion of giving feedback to the user that we couldn't figure out the server's version because it was disconnected. So reducing the timeout from 3 seconds to possibly 1 second should do the trick instead of only retrieving the client version by default

2024-05-08 21:23 UTC, closed without merging