Update version.go to fix running a server built from source
bacalhau-project/bacalhau pull request #4170
Opened 2024-06-29 23:04 UTC by js-ts

currently when you try to run a server using the binary built from  source and try to run any command it throws this error, this error can be fixed by  stripping the metadata from version before parsing

To run test jobs against the local cluster which uses the build from source binary without getting this error everytime a job is run this error needs to be fixed

bin/darwin/amd64/bacalhau serve --node-type compute --node-type requester

bin/darwin/amd64/bacalhau node list
```
Error: failed request: Unexpected response code: 403 ({
  "Error": "Client version is outdated. Update your client",
  "MinVersion": "1.4.0",
  "ClientVersion": "1.4.0-6-g081eabfba",
  "ServerVersion": "1.4.0-6-g081eabfba"
})
```

2024-07-02 00:05 UTC, frrist reviewed
The problem here is that versions with a pre-release are considered less than versions without a prerelease all other fields equal. i.e. `v1.4.0` > `v1.4.0-abc123`. I believe the correct change here is to strip the pre-release tag from the client before doing the comparison. @wdbaruni wdyt?

2024-07-02 00:07 UTC, frrist requested changes

2024-07-02 00:07 UTC, frrist commented on pkg/publicapi/middleware/version.go
> +}
Please remove this method, suggestion on replacement below

2024-07-02 00:07 UTC, frrist commented on pkg/publicapi/middleware/version.go
> +			clientVersion, err := parseVersion(cVersion[0])
We should instead make a client version with the pre-release tag removed via `clientVersion.SetPrerelease("")`

2024-07-29 14:42 UTC, js-ts commented
@frrist

2024-08-07 16:36 UTC, frrist requested changes

2024-08-07 16:36 UTC, frrist commented on pkg/publicapi/middleware/version.go
> +			diff := serverVersion.Compare(strippedClientVersion)
we don't want to strip the client version here, this method is for logging the version of the request received from the client. Please revert this change.

2024-08-07 16:36 UTC, frrist commented on pkg/publicapi/middleware/version.go
> +
```suggestion
func stripPreRelease(versionStr string) (*semver.Version, error) {
	v, err := semver.NewVersion(versionStr)
	if err != nil {
		return version.Unknown, fmt.Errorf("failed to parse client version: %w", err)
	}
	strippedVersion, err := v.SetPrerelease("")
	if err != nil {
		return version.Unknown, fmt.Errorf("failed to strip pre-release version from client: %w", err)
	}
	return &strippedVersion, nil
}
```
please move this utility method to the bottom of the file.

2024-08-07 16:36 UTC, frrist commented on pkg/publicapi/middleware/version.go
> -			if clientVersion.LessThan(&minVersion) {
please use the suggested implementation of `stripPreRelease` here to both parse and strip the client version, i.e.
```go
// VersionCheckMiddleware returns a middleware that checks if the client version is at least minVersion.
func VersionCheckMiddleware(serverVersion, minVersion semver.Version) echo.MiddlewareFunc {
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			clientVersionStr := c.Request().Header.Get(apimodels.HTTPHeaderBacalhauGitVersion)
			if clientVersionStr == "" ||
				clientVersionStr == version.DevelopmentGitVersion ||
				clientVersionStr == version.UnknownGitVersion {
				// allow the request to pass through
				return next(c)
			}

			clientVersion, err := stripPreRelease(clientVersionStr)
			if err != nil {
				return c.JSON(http.StatusBadRequest, map[string]string{
					"Error": "Invalid client version " + clientVersionStr,
				})
			}

			if clientVersion.LessThan(&minVersion) {
				// Client version is less than the minimum required version
				return c.JSON(http.StatusForbidden, VersionCheckError{
					Error:         "Client version is outdated. Update your client",
					MinVersion:    minVersion.String(),
					ClientVersion: clientVersion.String(),
					ServerVersion: serverVersion.String(),
				})
			}

			// Client version is acceptable, proceed with the request
			return next(c)
		}
	}
}
```

2024-09-24 06:38 UTC, wdbaruni commented
I don't think this is an issue anymore

2024-09-24 06:38 UTC, closed without merging