refactor: read installationID from new location
bacalhau-project/bacalhau pull request #4451
Opened 2024-09-17 22:34 UTC by frrist

- must follow: https://github.com/bacalhau-project/getbacalhauorg/pull/37

2024-09-18 06:16 UTC, wdbaruni requested changes

2024-09-18 06:16 UTC, wdbaruni commented on pkg/repo/fs.go
> +	}
why are we storing the installationID in the repo?

2024-09-18 06:16 UTC, wdbaruni commented on pkg/repo/fs.go
> +
why are we persisting one if not found? As we discussed before, installationID should only be provided by the installation script and we won't generate one on our own when running bacalhau. That will be handled by the instanceID

2024-09-18 06:16 UTC, wdbaruni commented on pkg/repo/installationid.go
> +		idFile = filepath.Join(configDir, "bacalhau", "installation_id")
lets use this for mac as well

2024-09-18 06:16 UTC, wdbaruni commented on pkg/repo/installationid.go
> +	os.UserCacheDir()
not used

2024-09-23 20:29 UTC, frrist commented on pkg/repo/installationid.go
> +		idFile = filepath.Join(configDir, "bacalhau", "installation_id")
we do on line 13

2024-09-23 20:38 UTC, frrist commented
closing in favor of https://github.com/bacalhau-project/bacalhau/pull/4450

2024-09-23 20:38 UTC, closed without merging